version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_VERSION: "1.0.0"
    image: media:1.0.0
    ports:
      - "3999:3999"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=e133535a08e864df3c9af422e3a1878f
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
      - ./minio-config/:/root/.minio
    command: server --console-address ":9001" /data
volumes:
  minio-data: